services:
  db:
    image: postgres:17 
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_PORT: ${DATABASE_PORT}
    env_file: .env
    attach: false

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
    attach: false

  api:
    image: stukez12/day-by-day-tracker-api:${APP_VERSION}
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - app-network
    volumes:
      - ./backend:/api/backend
    env_file:
      - .env.prod
    command: uvicorn backend.main:app --host ${API_HOST} --port ${API_PORT}

  frontend:
    image: stukez12/day-by-day-tracker-frontend:${APP_VERSION}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      VITE_BACKEND_HOST: ${API_HOST}
      VITE_BACKEND_PORT: ${API_PORT}
    env_file: .env.prod


networks:
  app-network:


volumes:
  pgadmin-data:
  postgres_data:
