name: Deployment

on:
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: "App version / tag"
  #       required: true

  release:
    types: [published]

  # workflow_run:
  #   workflows: []
  #   types:
  #     - completed

jobs:
  deployment:
    # # Uncomment when using "on: workflow_run:"
    # if: github.event.workflow_run.event == 'release' || github.event_name == 'release'

    name: Deployment
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - context: "."
            file: backend/Dockerfile
            image: "day-by-day-tracker-api"
            platforms: linux/amd64,linux/arm64
          - context: "frontend"
            file: frontend/Dockerfile
            image: "day-by-day-tracker-frontend"
            platforms: linux/amd64,linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Create Tags
        id: tags
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}
          # Enable when workflow is set to release
          tags: "${{ github.event.release.tag_name }}"

          # # Enable when workflow is set to workflow_dispatch
          # tags: type=raw,value=${{ github.event.inputs.version }}

      - name: Docker Build Images
        uses: docker/build-push-action@v6.9.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ steps.tags.outputs.tags }}
          labels: ${{ steps.tags.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
